build: updating yaml for using container

diff --git a/.github/workflows/useContainer.yml b/.github/workflows/useContainer.yml
--- a/.github/workflows/useContainer.yml
+++ b/.github/workflows/useContainer.yml
@@ -32,3 +32,17 @@ jobs:
             . bin/set-path.sh &&
             AUTOIG=\$(pwd) &&
             ./check.sh"
+
+      # if script fails reject PR
+      - name: Fail
+        if: ${{ failure() }}
+        run: |
+          echo "Check.sh failed, rejecting PR."
+          exit 1
+
+      # if script passes approve PR
+      - name: Pass
+        if: ${{ success() }}
+        run: |
+          echo "Check.sh passed, allowing PR."
+          exit 0
